import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { supabase } from '../lib/supabase';

type Service = { id:string; name:string; base_price:number };
export default function Book() {
  const { service: initial } = useLocalSearchParams<{service?:string}>(); const [services,setServices]=useState<Service[]>([]); const [serviceId,setServiceId]=useState(initial ?? ''); const [address,setAddress]=useState(''); const [notes,setNotes]=useState(''); const [date,setDate]=useState(new Date(Date.now()+86400000).toISOString().slice(0,10)); const [time,setTime]=useState('10:00'); const [loading,setLoading]=useState(false);
  useEffect(()=>{supabase.from('services').select('id,name,base_price').eq('is_active',true).order('sort_order').then(({data})=>setServices(data??[]))},[]);
  const submit=async()=>{ if(!serviceId||!address||!date||!time) return Alert.alert('Complete your booking','Please select a service and enter your appointment details.'); setLoading(true); const {data:{user}}=await supabase.auth.getUser(); if(!user){setLoading(false); return Alert.alert('Sign in required','Please create an account before confirming a booking.');} const startsAt=new Date(`${date}T${time}:00`).toISOString(); const {error}=await supabase.from('bookings').insert({customer_id:user.id,service_id:serviceId,scheduled_at:startsAt,address,notes,payment_method:'cash',status:'received'}); setLoading(false); if(error) return Alert.alert('Booking unavailable',error.message); Alert.alert('Booking received','We will confirm your appointment shortly.', [{text:'Done',onPress:()=>router.replace('/')}]); };
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.title}>YOUR APPOINTMENT</Text><Text style={styles.label}>SERVICE</Text><View style={styles.choices}>{services.map(s=><Pressable key={s.id} onPress={()=>setServiceId(s.id)} style={[styles.choice,serviceId===s.id&&styles.selected]}><Text style={[styles.choiceText,serviceId===s.id&&styles.selectedText]}>{s.name} · K{s.base_price}</Text></Pressable>)}</View><Text style={styles.label}>DATE (YYYY-MM-DD)</Text><TextInput value={date} onChangeText={setDate} style={styles.input} placeholder="2026-09-06" placeholderTextColor="#777"/><Text style={styles.label}>TIME (24 HOUR)</Text><TextInput value={time} onChangeText={setTime} style={styles.input} placeholder="10:00" placeholderTextColor="#777"/><Text style={styles.label}>SERVICE ADDRESS</Text><TextInput value={address} onChangeText={setAddress} style={styles.input} placeholder="Home, office, hotel or event address" placeholderTextColor="#777"/><Text style={styles.label}>NOTES (OPTIONAL)</Text><TextInput value={notes} onChangeText={setNotes} style={[styles.input,{height:96,textAlignVertical:'top'}]} multiline placeholder="Please bring black dye…" placeholderTextColor="#777"/><Text style={styles.note}>Payment method: Cash after service. Mobile money and card options can be activated securely through a Supabase payment function.</Text><Pressable onPress={submit} style={styles.button} disabled={loading}>{loading?<ActivityIndicator color="#0A0A0A"/>:<Text style={styles.buttonText}>CONFIRM BOOKING</Text>}</Pressable></ScrollView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#0A0A0A'},content:{padding:24,gap:10},title:{color:'#FFF',fontSize:26,fontWeight:'900',marginBottom:12},label:{color:'#D4AF37',fontSize:11,fontWeight:'800',letterSpacing:1.2,marginTop:12},choices:{gap:8},choice:{borderWidth:1,borderColor:'#373737',padding:13},selected:{borderColor:'#D4AF37',backgroundColor:'#211C0B'},choiceText:{color:'#DDD'},selectedText:{color:'#FFF',fontWeight:'700'},input:{borderWidth:1,borderColor:'#373737',color:'#FFF',padding:13,fontSize:15},note:{color:'#969696',fontSize:12,lineHeight:18,marginTop:8},button:{backgroundColor:'#D4AF37',padding:16,alignItems:'center',marginTop:16},buttonText:{fontWeight:'900',letterSpacing:1,color:'#0A0A0A'} });
