'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createClient } from '@supabase/supabase-js';
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL ?? '', process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '');
type Message = { id:string; customer_id:string; sender:'customer'|'admin'; body:string; created_at:string; profiles:{full_name:string|null;phone:string|null}|null };
export function AdminChat() {
 const [open,setOpen]=useState(false); const [messages,setMessages]=useState<Message[]>([]); const [selected,setSelected]=useState<string|null>(null); const [text,setText]=useState('');
 const load=async()=>{const {data}=await supabase.from('customer_admin_messages').select('id,customer_id,sender,body,created_at,profiles!customer_admin_messages_customer_id_fkey(full_name,phone)').order('created_at'); setMessages((data as unknown as Message[])??[]);};
 useEffect(()=>{void load();const channel=supabase.channel('admin-live-chat').on('postgres_changes',{event:'*',schema:'public',table:'customer_admin_messages'},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel);};},[]);
 const conversations=useMemo(()=>Array.from(new Map(messages.map(message=>[message.customer_id,message])).values()).sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()),[messages]);
 const activeId=selected??conversations[0]?.customer_id??null; const active=messages.filter(message=>message.customer_id===activeId); const client=conversations.find(item=>item.customer_id===activeId);
 const send=async(e:FormEvent)=>{e.preventDefault();if(!activeId||!text.trim())return;const body=text.trim();setText('');await supabase.from('customer_admin_messages').insert({customer_id:activeId,sender:'admin',body});};
 return <div className="adminChatRoot">{open&&<section className="adminChatPanel"><header><div><p>LIVE CUSTOMER CHAT</p><h3>Messages</h3></div><button onClick={()=>setOpen(false)}>×</button></header><div className="adminChatBody"><aside>{conversations.length?conversations.map(item=><button key={item.customer_id} className={item.customer_id===activeId?'active':''} onClick={()=>setSelected(item.customer_id)}><b>{item.profiles?.full_name||'Customer'}</b><span>{item.body}</span></button>):<p>No customer messages yet.</p>}</aside><main>{activeId?<><div className="adminChatClient"><b>{client?.profiles?.full_name||'Customer'}</b><span>{client?.profiles?.phone||'Live support conversation'}</span></div><div className="adminChatMessages">{active.map(message=><div key={message.id} className={'adminChatBubble '+message.sender}><p>{message.body}</p><small>{new Date(message.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></div>)}</div><form onSubmit={send}><input value={text} onChange={event=>setText(event.target.value)} placeholder="Reply to customer…"/><button>Send</button></form></>:<div className="adminChatEmpty">Select a customer conversation to reply.</div>}</main></div></section>}<button className="adminChatLauncher" onClick={()=>setOpen(value=>!value)}><span>✦</span>{open?'Close chat':'Live chat'}{conversations.length>0&&<i>{conversations.length}</i>}</button></div>;
}
